/**
 * List of contributors
 */
module.exports = [
  {
    "handle": "jhiggins",
    "lastName": "Higgins",
    "firstName": "Joseph",
    "email": "joseph.james.higgins@gmail.com",
    "contribution": 10.00,
  },
  {
    "handle": "ecandino",
    "lastName": "Candino",
    "firstName": "Eric",
    "email": "ecandino@gmail.com",
    "contribution": 9.75,
  },
  {
    "handle": "kpeltzer",
    "lastName": "Peltzer",
    "firstName": "Ken",
    "email": "kpeltzer@gmail.com",
    "contribution": 5.00,
  },
  {
    "handle": "dmazurek",
    "lastName": "Mazurek",
    "firstName": "Dean",
    "email": "dean@thrillist.com",
    "contribution": 5.00,
  },
  {
    "handle": "bjurgens",
    "lastName": "Jurgens",
    "firstName": "Brett",
    "email": "brett@brettjurgens.com",
    "contribution": 4.87,
  },
  {
    "handle": "agreen",
    "lastName": "Green",
    "firstName": "Alison",
    "email": "agreen@thrillist.com",
    "contribution": 5.00,
  },
  {
    "handle": "kedwards",
    "lastName": "Edwards",
    "firstName": "Kyle",
    "email": "edwards.kyle.a@gmail.com",
    "contribution": 6.66,
  },
  {
    "handle": "aahn",
    "lastName": "Ahn",
    "firstName": "Andrew",
    "email": "ahndrew.s@gmail.com",
    "contribution": 5.00,
  },
  {
    "handle": "gchenzion",
    "lastName": "Chen-Zion",
    "firstName": "Gil",
    "email": "gil.chenzion@gmail.com",
    "contribution": 5.00,
  },
  {
    "handle": "spenny",
    "lastName": "Penny",
    "firstName": "Schuyler",
    "email": "spenny@thrillist.com",
    "contribution": 5.00,
  },
  {
    "handle": "lashpole",
    "lastName": "Ashpole",
    "firstName": "Lauren",
    "email": "laurenashpole@gmail.com",
    "contribution": 5.00,
  },
  {
    "handle": "wbliss",
    "lastName": "Bliss",
    "firstName": "Wesley",
    "email": "wesley.bliss@gmail.com",
    "contribution": 10.00,
  },
  {
    "handle": "esankey",
    "lastName": "Sankey",
    "firstName": "Elizabeth",
    "email": "elizabeth@thrillist.com",
    "contribution": 10.00,
  },
  {
    "handle": "kboateng",
    "lastName": "Boateng",
    "firstName": "Kwadwo",
    "email": "boatengk@seas.upenn.edu",
    "contribution": 1.00,
  },
  {
    "handle": "esancha",
    "lastName": "Diaz Sancha",
    "firstName": "Eduardo",
    "email": "ed.sancha@gmail.com",
    "contribution": 5.00,
  },
  {
    "handle": "smervine",
    "lastName": "Mervine",
    "firstName": "Strider",
    "email": "stridermervine@gmail.com",
    "contribution": 6.00,
  },
  {
    "handle": "mhaarhaus",
    "lastName": "Haarhaus",
    "firstName": "Maximilian",
    "email": "mhaarhaus@thrillist.com",
    "contribution": 6.06,
  },
  {
    "handle": "kb",
    "lastName": "Bales",
    "firstName": "Kyle",
    "email": "masterjedi@gmail.com",
    "contribution": 0.0,
  }
];
